#
# Generic framework for controlling remote processors
#

obj-$(CONFIG_REMOTEPROC)		+= remoteproc.o
remoteproc-y				:= remoteproc_core.o
remoteproc-y				+= remoteproc_debugfs.o
remoteproc-y				+= remoteproc_virtio.o
remoteproc-y				+= remoteproc_elf_loader.o
obj-$(CONFIG_DUMMY_REMOTEPROC)		+= dummy_remoteproc.o
obj-$(CONFIG_DUMMY_LOCALPROC)		+= dummy_localproc.o dummy_trampoline_64.o
